# This is a basic workflow to help you get started with Actions

name: SAST COM PIPELINE SCANNER

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, release, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run compilação da aplicação
        run: | 
          mvn clean package
        working-directory: app
      # Runs a set of commands using the runners shell
      - name: Download API WRAPPER
        run: |
          curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -n pipeline-scan-LATEST.zip
      - name: Security scan
        run: |
          curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -n pipeline-scan-LATEST.zip
          ls target || true
          java -jar pipeline-scan.jar -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" -f "target/verademo-0.0.1-SNAPSHOT.jar" --fail_on_severity="Very High, High" || true
          zip -r verademo.zip target/*.war
          java -jar pipeline-scan.jar -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" -f "verademo.war" --fail_on_severity="Very High, High"
        working-directory: app
